### ISSUE TITLE
Feature : Add Karaoke mode

### ISSUE THREAD

**Issue by zarghol** [insidegui/AnimojiStudio#11]
Possible to choose song, play it synchronized with recording and display lyrics.

Advanced feature : add directly the music to the sound of the video

**Comment by insidegui** [comment]
It's here 🎉

Can you open a separate issue for the lyrics? Thanks!

**Comment by zarghol** [comment]
Awesome ! I thought to MusicKit with Apple Music (and lyrics), instead of Spotify, but I'll try to integrate it, If you don't use it.
The other issue is opened

**Comment by insidegui** [comment]
I tried Apple Music first, but unfortunately it does the audio playback on a separate process and the music has DRM, so I don't think it's possible to record the audio with the video like I do with Spotify.
