### ISSUE TITLE
Consider having all puppets active on selection, like in Photo Booth

### ISSUE THREAD

**Issue by LeoNatan** [insidegui/AnimojiStudio#13]
Cool stuff

Can more than one puppet be "Active" on screen? A cool effect would be to have all puppets follow the user's face on selection, like in PhotoBooth.

I don't have an X, so I cannot test and/or PR.

**Comment by insidegui** [comment]
Unfortunately it seems like only one puppet can be controlled at a time, but I'm planning on having a feature that allows you to switch puppets during recording.

**Comment by insidegui** [comment]
Switching puppets during recording is now possible, the other feature unfortunately is not feasible to implement.
