### ISSUE TITLE
Pre-X iPhone Support

### ISSUE THREAD

**Issue by abjurato** [insidegui/AnimojiStudio#15]
After yesterday's [hype](https://twitter.com/icanzilb/status/930803536551731202) about unencessity of frontal depth camera, I've decided to try running AnimojiStudio on my iPhone7+. Generally, I decided to place the AvatarKit framework inside the bundle of AnimojiStudio.

What I've tried to do:
1. deleted `front-depth-camera` from Info.plist, so Xcode will be able to install the app on my device, but _dyld_start throws exception because there is no AvatarKit.framework in iPhone7's system

2. so I excluded AvatarKit from iPhone X ipsw's dyld_shared_cache and tried to include it into project instead of your AvatarKit.framework with tbd in _General->Linked Frameworks and Libraries_. It depends on PrivateFrameworks/AvatarKit.framework which also does not exist on my device:
`dyld: Library not loaded: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
  Referenced from: /var/containers/Bundle/Application/5EE4DAFD-99C6-46C4-8D77-E86F69CD3C56/AnimojiStudio.app/AnimojiStudio
  Reason: image not found`

3. When I try to add excluded binary to _Embedded binaries_, I'm getting such error while linking:
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: file not in an order that can be processed (dyld_info out of place): /Users/arosencrantz/Downloads/AnimojiStudio-master/AnimojiStudio/AvatarKit/dyld_shared_cache_arm64.AvatarKit`. Same error I'm getting when trying to run `install_name_tool -change` on the excluded binary in order to change dependency path.

4. I've found AvatarKit.framework (which seems to contain different resources used by the framework binary) in /System/Library/PrivateFrameworks of ipsw, copied it into my project and added it to _Linked Frameworks and Libraries_ and checked that it presents in _Build Settings->Framework Search Paths_, but still getting `ld: framework not found AvatarKit` error while linking. This error always drives me crazy 💀

I'm not so keen in revers engineering, so the questions if this strategy is correct:
1. place AvatarKit.framework from PrivateFrameworks somewhere inside app bundle
2. change excluded from ipsw binary's dependency path to this place

If so, why the hell do those errors happen and what do they mean?

**Comment by insidegui** [comment]
It's not possible to run AvatarKit on devices other than iPhone X. It uses ARKit's facial tracking mechanism and that requires a TrueDepth camera. I know you can cover the sensors and it still works, but it doesn't change the fact that ARKit's facial tracking only runs on iPhone X.

It might be possible to do with some serious patching of ARKit/AvatarKit, but I'm not sure I'm able to do that and I want to focus my time on making a great app with cool features and a nice UI.

**Comment by abjurato** [comment]
Okay, got that. But is it possible in theory to extract private framework from ipsw and embed into app?

**Comment by insidegui** [comment]
I tried it before and couldn't make it work because of code signing issues.
