### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by sandeeptiwari77** [insidegui/AnimojiStudio#16]
Sliders for background color appear but only top Red slider is accessible. The remaining two sliders seem to be obscured by the Enable microphone and Background color buttons. Sliding the red slider and tapping anywhere else on the screen sets the color, but hitting the background color again raises an error
![img_c2ec9f050add-1](https://user-images.githubusercontent.com/20865212/32884244-4bd60a8c-ca7f-11e7-8805-1ed4c773ea41.jpeg)

**Comment by insidegui** [comment]
Fixed 🎉
