### ISSUE TITLE
Spotify search UI and authentication issues 

### ISSUE THREAD

**Issue by insidegui** [insidegui/AnimojiStudio#17]
Currently, when searching Spotify, there is no feedback while the results are loading. This can make it look like the app is broken. If the search fails for some reason, we should show the error to the user.

**Comment by icep87** [comment]
I'm unable to search with Spotify, getting follow message in the log: Spotify search error: Error Domain=com.spotify.ios-sdk Code=104 "(null)"

**Comment by puttin** [comment]
The problem seems to be `self.auth.session` is nil

**Comment by CKLAslan** [comment]
So does this work for anyone?

**Comment by CKLAslan** [comment]
So is there a fix? Something to try?  Any kind of response?  Or should I just delete the useless app?

**Comment by puttin** [comment]
For me the real problem is:

* `fun.animoji` is a bundle identifier I cannot create profile so that I cannot install it on my own device
* so I change to my own bundle identifier
* so Spotify client ID need to be my own
* so I need a Spotify secret swap service for that client ID

or Auth would never succeed. I haven't set up my own swap service to try out yet.

**Comment by williamli** [comment]
so what is the steps we need to do to get the Spotify integration working?
I changed the bundle identifier to I can export and deploy the app via Xcode...

PS: Is there a way to not change the bundle identifier and deploy the IPA directly into iPhone?

**Comment by Vincenzo21** [comment]
Me too, when I search something, I read this message in the log: Spotify search error: Error Domain=com.spotify.ios-sdk Code=104 "(null)"

Spotify Premium

**Comment by insidegui** [comment]
@puttin Is correct. I believe the issue is that the client ID for Spotify is associated with the bundle ID of the app. If you delete the Spotify app and log in using the web view, it works.

I'll update the readme with this information.
