### ISSUE TITLE
exported video is not imessage ready

### ISSUE THREAD

**Issue by iPhoNewsRO** [insidegui/AnimojiStudio#18]
hello, after recording like 20 seconds of animoji fun, tap the share screen and pick message. the resulting video won't be working on ios or macos (play button crossed on mac or just unknown file icon on ios).

**Comment by insidegui** [comment]
The videos produced are HEVC encoded, are you trying to watch them on iOS 10 or macOS Sierra?

**Comment by iPhoNewsRO** [comment]
i shared the video in a group with multiple people and i only got this issue once. maybe its a race condition?
