### ISSUE TITLE
Search Music didn't return anything

### ISSUE THREAD

**Issue by WilhelmVonEinzbern** [insidegui/AnimojiStudio#25]
Spotify account is already Premium. However, the search music function in karaoke mode didn't return any results.[](url)
<img width="1677" alt="screen shot 2017-11-26 at 18 01 48" src="https://user-images.githubusercontent.com/6170811/33242360-0a48ce6c-d2d4-11e7-8325-26a4d6d43d8e.png">

**Comment by insidegui** [comment]
Is this a duplicate of #17 ?

**Comment by WilhelmVonEinzbern** [comment]
Indeed ... Sorry, I didn't check #17.

**Comment by insidegui** [comment]
No problem :)
