### ISSUE TITLE
Spotify search not working

### ISSUE THREAD

**Issue by CKLAslan** [insidegui/AnimojiStudio#26]
I have a Spotify premium account installed and configured on my iPhone X. It works properly.

From AnimojiStudio when I click "Configure Karaoke", it opens Spotify, puts a big checkmark across the screen, then goes to the search screen.  No matter what I type in the search screen I get no results, no messages, no errors, no feedback, no nothing.

If I search for a song in Spotify without studio, it works fine.

**Comment by curiouskunal** [comment]
I am also having this issue

**Comment by insidegui** [comment]
Let's keep Spotify search/auth issues discussion on #17
