### ISSUE TITLE
Karaoke not working

### ISSUE THREAD

**Issue by gadgetgeek407** [insidegui/AnimojiStudio#29]
When I click configure karaoke and have mic off, it brings up the songs, i can either press play and song plays, if I select the song itself and press the screen to record I cannot hear the song playing and whatever records it does not have the song, is this a broken feature cause does not seem to work from my iphone x no matter what I try.

**Comment by insidegui** [comment]
Currently, you need to press the little play icon before you start recording. The need to do this will be removed in a future update.

**Comment by insidegui** [comment]
![img_e89d5f640cce-1](https://user-images.githubusercontent.com/67184/34619315-dfac400c-f228-11e7-98b2-094a2cf98463.jpeg)

For reference, this is the button you use to start playing the song before recording.

**Comment by gadgetgeek407** [comment]
I don't have the play button next to configure karaoke. Maybe this is the issue? How can I fix this?

DISCLAIMER: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

Save a tree by reducing the amount of paper you print.

Warmest Regards,

Bilal
Home of Quality Pre-Owned Government  Vehicles
Feel Free To Check Our Website Below & Read Testimonials From Many of Our Satisfied Customers!
www.sunshineautomall.com
(407) 718-9900
