### ISSUE TITLE
App doesn't work with iOS 11.2.2

### ISSUE THREAD

**Issue by jsyw59** [insidegui/AnimojiStudio#30]
As described in title. iOS 11.2.5 is coming soon though, so probably best see if it's compatible then?

**Comment by insidegui** [comment]
Can you provide more detail?

I'm running 11.2.2 and it works just fine.

**Comment by jsyw59** [comment]
Sorry my bad for not giving more details. Mine just quits as soon as I open the app. I might try reinstalling the app and see if the problem presists

**Comment by insidegui** [comment]
Are you perhaps trying to run it on a device that's not an iPhone X?

**Comment by jsyw59** [comment]
Nope, been running it fine on my iPhone X prior to 11.2.2

On 12 Jan 2018, at 18:23, Guilherme Rambo <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you perhaps trying to run it on a device that's not an iPhone X?

**Comment by jsyw59** [comment]
Tried to reinstall it, works fine now. Thank you for your help anyway :)

**Comment by insidegui** [comment]
Great 🎉
