### ISSUE TITLE
Unable to install on iOS 11.3. Beta 2

### ISSUE THREAD

**Issue by d-knapke** [insidegui/AnimojiStudio#31]
I'm using an iPhone X with iOS 11.3 public beta 2. I tried to install AnimojiStudio using Cydia Impactor and i got the following error:
![grafik](https://user-images.githubusercontent.com/36566093/36341377-a4011294-13ed-11e8-8839-219913b3d909.png)

**Comment by insidegui** [comment]
File a bug report with Impactor
