### ISSUE TITLE
Unable to install on iOS 11.3. Beta 3

### ISSUE THREAD

**Issue by d-knapke** [insidegui/AnimojiStudio#33]
I'm using an iPhone X with iOS 11.3 public beta 3. I've tried to install AnimojiStudio using Cydia Impactor and i got the following error:

![36341377-a4011294-13ed-11e8-8839-219913b3d909](https://user-images.githubusercontent.com/36566093/36630202-d59e9cde-1962-11e8-837e-bbed30c46b27.png)

Log file from Impactor: [animojistudio.txt](https://github.com/insidegui/AnimojiStudio/files/1754332/animojistudio.txt)

**Comment by insidegui** [comment]
I don’t help with installation issues. This is a bug in Cydia Impactor
