### ISSUE TITLE
Unable to compile code

### ISSUE THREAD

**Issue by ramkrishna880** [insidegui/AnimojiStudio#34]
Hi, I downloaded this repo and try to compile but there are few errors and getting failed from compiling.
Please help me. below is my error screen shot
<img width="787" alt="screen shot 2018-04-04 at 12 35 46 pm" src="https://user-images.githubusercontent.com/3078050/38288688-bd224c26-3804-11e8-86ff-578bb28c3aa7.png">

**Comment by zarghol** [comment]
try for a real device, not the simulator (x86_64 is the simulator), and AvatarKit require an iOS device
