### ISSUE TITLE
Memoji

### ISSUE THREAD

**Issue by karthickchirra** [insidegui/AnimojiStudio#36]
Is there a way we can get Memojis into this!!

**Comment by yomybaby** [comment]
I tried to find a way to support memoji but I couldn't. Let me know if you have any hints.
@insidegui Do you know have any little hint? 😁 
Thank you for your efforts.

**Comment by insidegui** [comment]
Implemented in #38

**Comment by derekschinke** [comment]
Unfortunately, doesn't support existing Memoji in iMessage, nor deleting or editing of created emojis. It also opens the Memoji view twice when selecting a Memoji.

**Comment by insidegui** [comment]
> Unfortunately, doesn't support existing Memoji in iMessage

That's impossible because of entitlements
