### ISSUE TITLE
Code signing question

### ISSUE THREAD

**Issue by LouieGasparini** [insidegui/AnimojiStudio#41]
I am getting the following code signing errors when trying to compile:  (any suggestions are appreciated).

No account for team "8C7439RJLG".
Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

No profiles for 'fun.Animoji' were found
Xcode couldn't find any iOS App Development provisioning profiles matching 'fun.Animoji'.

![screenshot_01](https://user-images.githubusercontent.com/16375465/46049008-08a4e900-c0e1-11e8-824b-ec2c8ef133db.jpg)

**Comment by insidegui** [comment]
Change the bundle identifier to something custom and select a different team for code signing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LouieGasparini** [comment]
Thank you that seems to work...  But now I get an error that I need to add arm64e to my build settings, which I did add but still get the error.. Any suggestions there?  I do choose the destination to be the iPhone (unsupported architecture).

![screenshot_04](https://user-images.githubusercontent.com/16375465/46115376-7fa6b400-c1ab-11e8-8f32-7bd5184b4af0.jpg)

![screenshot_05](https://user-images.githubusercontent.com/16375465/46115381-859c9500-c1ab-11e8-8144-315358111cdf.jpg)

![screenshot_07](https://user-images.githubusercontent.com/16375465/46115385-8a614900-c1ab-11e8-90cc-c63b13256700.jpg)

**Comment by insidegui** [comment]
You're trying to run it on an unsupported device. Animoji can only be used on iPhone X, XS or XS Max.

**Comment by LouieGasparini** [comment]
It is the new iPhone XS Max.  Animoji works just fine in texts.

**Comment by LouieGasparini** [comment]
I need to upgrade Xcode and it wants me to also upgrade to OS Mojave.  so doing that now.  Think this should fix my problem. Thx for the help.

**Comment by insidegui** [comment]
Awesome, let me know if that works
